### ISSUE TITLE
Function name does not follow lint rules

### ISSUE THREAD

**Issue by Lucasljungberg** [Lucasljungberg/sef18group15-refactor#16]
https://github.com/Lucasljungberg/sef18group15-refactor/blob/b24d58ef24261102efe4d6aa6f429e0f1c8f5137/src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java#L348-L363

I think rules says it should be camel casing on function names

**Comment by Lucasljungberg** [comment]
The relevant line is:  
- [ ] 308

**Comment by sareng** [comment]
I think the issue is rather that is starts with a big U?

**Comment by Lucasljungberg** [comment]
Fixed in #20
